debug: false

server:
  port: 8091

spring:
  application:
    name: Eureka Server
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8091/eureka/


